name: Fronten_CD Deploy
on:
    push:
        branches: [ main ]

# env:
#    AWS_REGION: ap-southeast-2
#    S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#    CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CF_DIST_ID }}
#    BUILD_DIR: dist

jobs:
    deploy:
        runs-on: ubuntu-lastest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
            - uses: pnpm/action-setup@v2
              with:
                version: 9
                run_install: false 
            - name: install deps #dependencies
              run: pnpm build
              working-directory: frontend
            - name: Build
              run: pnpm build
              working-directory: frontend
            - name: Configure AWS (OIDC + AssumeRole) #OpenID Connect
              if: ${{ env.S3_BUCKET != ''}}
              uses: aws-actions/configure-aws-credentials@v4 #GitHub log in AWS
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }} #AWS IAM Role ARN
                aws-region: ${{ env.AWS_REGION }} 
                role-session-name: frontend-deploy
            - name: Sync to S3 #upload to S3
              run: aws s3 sync "dist" "s3://${S3_BUCKET}/" --delete --exact-timestamps --only-show-errors --metadata-directive REPLACE --cache-control "max-age=300""
            - name: Invalidate CloudFront #Clear Cache
              if: ${{ env.CLOUDFRONT_DISTRIBUTION_ID != ''}}
              run: |
                aws cloudfront create-invalidation \
                  --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" \
                  --paths "/index.html" "/"
                
